apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: sodium
  template:
    metadata:
      labels:
        app: sodium

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: sodium
