apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
patches:
  - target:
      kind: .*
      name: backend
    patch: |-
      - op: replace
        path: /metadata/name
        value: oxygen
patchesStrategicMerge:
  - patch.yaml
