apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: oxygen
  template:
    spec:
      serviceAccountName: oxygen
    metadata:
      labels:
        app: oxygen

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: oxygen
