apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: hydrogen
  template:
    metadata:
      labels:
        app: hydrogen

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: hydrogen
