apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: chlorine
  template:
    metadata:
      labels:
        app: chlorine

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: chlorine
